module.exports = {
	IPC: {
		LOAD_FILE_LIST: 'LOAD_FILE_LIST',
		DOWNLOAD: 'DOWNLOAD',
		ABORT: 'ABORT',
		COPY_PROGRESS: 'COPY_PROGRESS',
		OPEN_DIR_DIALOG: 'OPEN_DIR_DIALOG',
		DOWNLOAD_DIR_CHANGED: 'DOWNLOAD_DIR_CHANGED'
	}
};

